# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 03:57
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Page = apps.get_model('wiki', 'Page')
    db_alias = schema_editor.connection.alias
    Page.objects.using(db_alias).create(
        title='Welcome to Overwiki',
        slug='home',
        content='This is your homepage.'
    )

def backwards(apps, schema_editor):
    Page = apps.get_model('wiki', 'Page')
    db_alias = schema_editor.connection.alias
    Page.objects.using(db_alias).get(slug='home').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20170419_0356'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
