FROM python:3.6.4-alpine

ENV PYTHONUNBUFFERED 1

ADD requirements.txt /requirements.txt

RUN apk update
RUN apk upgrade
RUN apk add --update gcc linux-headers musl-dev postgresql-dev

RUN mkdir /django
WORKDIR /django
ADD . /django

RUN pip install -r requirements.txt
